#!/bin/bash

### BEGIN INIT INFO
# Provides:          atlassian-status
# X-Interactive:     true
# Short-Description: Status for all Atlassian products
### END INIT INFO

#
# Configuration
#
readonly SCRIPT_DIRPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#
# Perform passed action to function
#
doAction() {
        action="${1}"

        if [ $(has_crowd) == 1 ] && [ $action == "start" ]; then
                ${SCRIPT_DIRPATH}/atlassian-crowd "${action}"
                sleep 5
        fi

        for f in ${SCRIPT_DIRPATH}/atlassian-*; do
                if [ $(basename "${f}") != $(basename "${0}") ]; then
                        if [[ ( $action == "start" || $action == "stop" ) && "${f}" == "${SCRIPT_DIRPATH}/atlassian-crowd" ]]; then
                                continue;
                        fi
                        
                        ${f} "${action}"
                fi
        done

        if [ $(has_crowd) == 1 ] && [ $action == "stop" ]; then
                sleep 5
                ${SCRIPT_DIRPATH}/atlassian-crowd "${action}"
        fi
}

#
# Check if user has crowd
#
has_crowd() {
        ls ${SCRIPT_DIRPATH}/atlassian-* | grep "crowd" > /dev/null;
        
        if [ $? -eq 0 ]; then
                echo 1
        else
                echo 0
        fi
}

#
# Perform start
#
start() {
        doAction "start";
}

#
# Perform stop
#
stop() {
        doAction "stop";
}

#
# Perfom retrieval of status
#
status() {
        doAction "status";
}

#
# Stop/start/status action selector
#
case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        status)
                status
                ;;
        *)
                echo "Usage: ${0} [start|stop|restart|status]"
esac

#
# Exit with zero return value
#
exit 0

# EOF
